name = "The PNC Games"
logo = "https://42lab-us-cdn.sunborngame.com/website/us_pc/roll/logo1_c.png"
districts = [
    { name = "Eosphorous Faction", color = "#ff1d00" },
    { name = "Hesperus Faction", color = "#ff7b00" },
    { name = "Trader Collective", color = "#ffd800" },
    { name = "Exiles", color = "#c7ff00" },
    { name = "Guardians", color = "#6aff00" },
    { name = "Rossum", color = "#0cff00" },
    { name = "Cyclopes", color = "#00ff50" },
    { name = "Helios", color = "#00ffae" },
    { name = "Enigma", color = "#00f2ff" },
    { name = "Pierides", color = "#0094ff" },
    { name = "Burbank", color = "#0037ff" },
    { name = "Copley", color = "#2600ff" },
    { name = "Ascension", color = "#8300ff" },
    { name = "Null Area", color = "#e100ff" },
    { name = "Neural Cloud Discord", color = "#ff00bf" },
    { name = "MICA HQ", color = "#ff0061" },
]

[[cast]]
name = "Machlian"
nickname = "Machlian"
gender = 0
image = "https://i.imgur.com/yYVob0Y.png"
dead_image = "https://i.imgur.com/MYwjcEM.png"

[[cast]]
name = "Xinghuan"
nickname = "Xinghuan"
gender = 0
image = "https://cdn.discordapp.com/emojis/1151854189203443712.png"
dead_image = "https://i.imgur.com/bRiVmnX.png"

[[cast]]
name = "Florence"
nickname = "Florence"
gender = 0
image = "https://i.imgur.com/w586Mai.png"
dead_image = "https://i.imgur.com/ixmFKIP.png"

[[cast]]
name = "Helix"
nickname = "Helix"
gender = 0
image = "https://cdn.discordapp.com/emojis/1059230395234783242.png"
dead_image = "https://i.imgur.com/I4iuUCG.png"

[[cast]]
name = "Kuro Gaming"
nickname = "Kuro Gaming"
gender = 0
image = "https://i.imgur.com/PbZbEer.png"
dead_image = "https://i.imgur.com/a7MYvGG.png"

[[cast]]
name = "Karnma"
nickname = "Karnma"
gender = 1
image = "https://i.imgur.com/HLndN16.png"
dead_image = "https://i.imgur.com/5HYzsa1.png"

[[cast]]
name = "Rintard"
nickname = "Rintard"
gender = 1
image = "https://i.imgur.com/pHbieEgh.jpg"
dead_image = "https://i.imgur.com/HAeKmjVh.jpg"

[[cast]]
name = "William"
nickname = "William"
gender = 1
image = "https://i.imgur.com/aKmdpSO.png"
dead_image = "https://i.imgur.com/oYxRMHu.png"

[[cast]]
name = "Wolfy"
nickname = "Wolfy"
gender = 0
image = "https://i.imgur.com/LDwIxmG.png"
dead_image = "https://i.imgur.com/fTFzNbX.png"

[[cast]]
name = "Hesperus"
nickname = "Hesperus"
gender = 1
image = "https://i.imgur.com/CwPXFab.png"
dead_image = "https://i.imgur.com/yYnhK97.png"

[[cast]]
name = "Tech."
nickname = "Tech."
gender = 4
image = "https://i.imgur.com/1g8jg41.gif"
dead_image = "https://i.imgur.com/AENpXzd.png"

[[cast]]
name = "Kekdated"
nickname = "Kekdated"
gender = 0
image = "https://i.imgur.com/CW57G5A.png"
dead_image = "https://i.imgur.com/twvSKsu.png"

[[cast]]
name = "Yuwulena"
nickname = "Yuwulena"
gender = 0
image = "https://i.imgur.com/MvRW33g.png"
dead_image = "https://i.imgur.com/kjeroul.png"

[[cast]]
name = "Colphne"
nickname = "Colphne"
gender = 0
image = "https://i.imgur.com/DPJbXAC.png"
dead_image = "https://i.imgur.com/VSSFjfx.png"

[[cast]]
name = "Raymond"
nickname = "Raymond"
gender = 1
image = "https://i.imgur.com/WFUXXkh.png"
dead_image = "https://i.imgur.com/aVwQWRq.png"

[[cast]]
name = "Nora"
nickname = "Nora"
gender = 0
image = "https://cdn.discordapp.com/emojis/1005020148769501245.png"
dead_image = "https://i.imgur.com/wrZcGz2.png"

[[cast]]
name = "Jiangyu"
nickname = "Jiangyu"
gender = 0
image = "https://i.imgur.com/rbC84zJ.png"
dead_image = "https://i.imgur.com/0pzVmYy.png"

[[cast]]
name = "Maya"
nickname = "Maya"
gender = 4
image = "https://i.imgur.com/Zjqvqn7.png"
dead_image = "https://i.imgur.com/Eol1wpy.png"

[[cast]]
name = "Selra"
nickname = "Selra"
gender = 1
image = "https://i.imgur.com/550OT3a.png"
dead_image = "https://i.imgur.com/VjN3FiV.png"

[[cast]]
name = "Destiny"
nickname = "Destiny"
gender = 4
image = "https://i.imgur.com/6bQT34L.png"
dead_image = "https://i.imgur.com/qlQxJKc.png"

[[cast]]
name = "Taco"
nickname = "Taco"
gender = 1
image = "https://i.imgur.com/jq7rBcE.png"
dead_image = "BW"

[[cast]]
name = "Fodith"
nickname = "Fodith"
gender = 1
image = "https://i.imgur.com/OwYPJzK.png"
dead_image = "https://i.imgur.com/nUvWD0C.png"

[[cast]]
name = "Hubbles"
nickname = "Hubbles"
gender = 0
image = "https://cdn.discordapp.com/emojis/1175947226418249749.png"
dead_image = "https://i.imgur.com/o4jjuRF.png"

[[cast]]
name = "Prof. SoCKs"
nickname = "Prof. SoCKs"
gender = 1
image = "https://i.imgur.com/ZgnO2Pdh.jpg"
dead_image = "https://i.imgur.com/1Ivy6bM.png"

[[cast]]
name = "Daiyan"
nickname = "Daiyan"
gender = 0
image = "https://i.imgur.com/vAiJEde.png"
dead_image = "https://i.imgur.com/wrFiryh.png"

[[cast]]
name = "Old Hag"
nickname = "Old Hag"
gender = 0
image = "https://i.imgur.com/wfYxCYo.png"
dead_image = "https://i.imgur.com/L6lEAXO.png"

[[cast]]
name = "Reissi"
nickname = "Reissi"
gender = 0
image = "https://cdn.discordapp.com/emojis/1005022496086564924.png"
dead_image = "https://i.imgur.com/388sp2bh.jpg"

[[cast]]
name = "Tsathy"
nickname = "Tsathy"
gender = 0
image = "https://i.imgur.com/RaTGmbB.png"
dead_image = "https://i.imgur.com/yu0cuaI.png"

[[cast]]
name = "Instructor Python"
nickname = "Instructor Python"
gender = 1
image = "https://cdn.discordapp.com/emojis/1065921438000881674.png"
dead_image = "https://i.imgur.com/0LWWdHd.png"

[[cast]]
name = "Mega Sweat"
nickname = "Mega Sweat"
gender = 4
image = "https://i.imgur.com/LkbinO1.png"
dead_image = "BW"

[[cast]]
name = "Neco Sol"
nickname = "Neco Sol"
gender = 0
image = "https://i.imgur.com/hiLgl7A.png"
dead_image = "https://i.imgur.com/3TaW6by.png"

[[cast]]
name = "Undine's Walking Garbage"
nickname = "Undine's Walking Garbage"
gender = 1
image = "https://i.imgur.com/Wdxb4uh.png"
dead_image = "https://i.imgur.com/TJ64Yln.png"

[[cast]]
name = "Majima when he"
nickname = "Majima when he"
gender = 1
image = "https://i.imgur.com/P53gc1h.png"
dead_image = "https://i.imgur.com/MUY1fCN.png"

[[cast]]
name = "Dupin"
nickname = "Dupin"
gender = 1
image = "https://cdn.discordapp.com/emojis/1045283406155632661.png"
dead_image = "https://i.imgur.com/qr4cQ7b.png"

[[cast]]
name = "Ksenia"
nickname = "Ksenia"
gender = 0
image = "https://i.imgur.com/eAWlCMn.png"
dead_image = "https://i.imgur.com/gVvUmp0.png"

[[cast]]
name = "RealComedian"
nickname = "RealComedian"
gender = 1
image = "https://i.imgur.com/ZHLH0ay.png"
dead_image = "https://i.imgur.com/TraPKki.png"

[[cast]]
name = "NotSoShou"
nickname = "NotSoShou"
gender = 1
image = "https://i.imgur.com/rFCJonu.png"
dead_image = "https://i.imgur.com/YdzwOe7.png"

[[cast]]
name = "Rinye"
nickname = "Rinye"
gender = 4
image = "https://i.imgur.com/xCMvQdi.png"
dead_image = "https://i.imgur.com/3FpK2Kv.png"

[[cast]]
name = "Horizon spray"
nickname = "Horizon spray"
gender = 0
image = "https://i.imgur.com/2ZqSBI9.png"
dead_image = "https://i.imgur.com/PpV0qH2.png"

[[cast]]
name = "Twigs"
nickname = "Twigs"
gender = 0
image = "https://i.imgur.com/a2HQrai.png"
dead_image = "https://i.imgur.com/XfvKBtJ.png"

[[cast]]
name = "Raph"
nickname = "Raph"
gender = 1
image = "https://i.imgur.com/3VuPzWx.png"
dead_image = "https://i.imgur.com/S6f5wCT.png"

[[cast]]
name = "Lizzy"
nickname = "Lizzy"
gender = 0
image = "https://i.imgur.com/1vW4L2a.png"
dead_image = "BW"

[[cast]]
name = "Griffin"
nickname = "Griffin"
gender = 1
image = "https://i.imgur.com/epXEqCL.png"
dead_image = "https://i.imgur.com/yIYkg61.png"

[[cast]]
name = "Nina"
nickname = "Nina"
gender = 0
image = "https://i.imgur.com/X3BM59z.png"
dead_image = "https://i.imgur.com/iXO86Ys.png"

[[cast]]
name = "Kimie when she"
nickname = "Kimie when she"
gender = 0
image = "https://i.imgur.com/Qd2hGAG.png"
dead_image = "https://i.imgur.com/UGl5TDo.png"

[[cast]]
name = "Catto"
nickname = "Catto"
gender = 0
image = "https://i.imgur.com/L6pDxJq.png"
dead_image = "https://i.imgur.com/XoPVzGi.png"

[[cast]]
name = "Stay"
nickname = "Stay"
gender = 4
image = "https://i.imgur.com/F3a2o1L.png"
dead_image = "https://i.imgur.com/iaObKgR.png"

[[cast]]
name = "Kruyger"
nickname = "Kruyger"
gender = 1
image = "https://i.imgur.com/stGU0lV.png"
dead_image = "https://i.imgur.com/BRBtWHQ.png"

[[cast]]
name = "Baba Lyuba"
nickname = "Baba Lyuba"
gender = 0
image = "https://i.imgur.com/nKWymLh.png"
dead_image = "https://i.imgur.com/tr00c1S.png"

[[cast]]
name = "Acez"
nickname = "Acez"
gender = 1
image = "https://i.imgur.com/s3LesgJ.png"
dead_image = "https://i.imgur.com/wzERPuo.png"

[[cast]]
name = "Hatsus"
nickname = "Hatsus"
gender = 0
image = "https://cdn.discordapp.com/emojis/1047931018134442134.png"
dead_image = "https://i.imgur.com/PIWfRB2h.jpg"

[[cast]]
name = "Tom Kruise"
nickname = "Tom Kruise"
gender = 4
image = "https://i.imgur.com/ucJat8l.png"
dead_image = "https://i.imgur.com/lFCan3q.png"

[[cast]]
name = "Sopmod"
nickname = "Sopmod"
gender = 0
image = "https://i.imgur.com/6iAruxj.png"
dead_image = "https://i.imgur.com/MW1ShLV.png"

[[cast]]
name = "G11"
nickname = "G11"
gender = 0
image = "https://i.imgur.com/DDRKFqu.png"
dead_image = "https://i.imgur.com/747rJAe.png"

[[cast]]
name = "Iny"
nickname = "Iny"
gender = 1
image = "https://i.imgur.com/Kcd0Lfa.png"
dead_image = "BW"

[[cast]]
name = "Kiryu"
nickname = "Kiryu"
gender = 1
image = "https://i.imgur.com/bcAVQGU.png"
dead_image = "https://i.imgur.com/WL0gBqe.png"

[[cast]]
name = "Uranus"
nickname = "Uranus"
gender = 1
image = "https://i.imgur.com/QkhdUUd.png"
dead_image = "https://i.imgur.com/uytnCzd.png"

[[cast]]
name = "CluKat"
nickname = "CluKat"
gender = 2
image = "https://i.imgur.com/CAdLvbS.png"
dead_image = "https://i.imgur.com/I1V4SfO.png"

[[cast]]
name = "Zancyin"
nickname = "Zancyin"
gender = 0
image = "https://cdn.discordapp.com/emojis/1005036492617420800.png"
dead_image = "https://i.imgur.com/o7w7cus.png"

[[cast]]
name = "Based Artist"
nickname = "Based Artist"
gender = 0
image = "https://i.imgur.com/ULhktOE.png"
dead_image = "https://i.imgur.com/gkykDfp.png"

[[cast]]
name = "Taisch"
nickname = "Taisch"
gender = 0
image = "https://i.imgur.com/nTkA6LT.png"
dead_image = "https://i.imgur.com/1wCvwH6.png"

[[cast]]
name = "Gin Mackarel"
nickname = "Gin Mackarel"
gender = 1
image = "https://cdn.discordapp.com/emojis/1062367254274125896.png"
dead_image = "https://i.imgur.com/TpHxPEwh.jpg"

[[cast]]
name = "Akismile"
nickname = "Akismile"
gender = 1
image = "https://cdn.discordapp.com/emojis/1005044933322866708.png"
dead_image = "https://i.imgur.com/2rHUlbs.png"

[[cast]]
name = "Harry"
nickname = "Harry"
gender = 1
image = "https://i.imgur.com/jfMcabn.png"
dead_image = "https://i.imgur.com/6pJTIN3.png"
