[project]
name = "NINA"
version = "0.1.1"
description = "This is a project that provides both a place for people to seek information about their favorite dolls. It just happens to also have a Battle Royale Simulation Utility."
authors = [{ name = "Tech. TTGames", email = "50541739+Tech-TTGames@users.noreply.github.com" }]
requires-python = ">=3.12,<4"
readme = "README.md"
license = "EPL-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "colorama>=0.4.6,<0.5",
    "discord-py>=2.6.4,<3",
    "aiohttp[speedups]>=3.14.3,<4",
    "pillow>=12.2.0,<13",
    "text-to-owo>=2.0.1,<3",
    "mkdocs-material>=9.7.6,<10",
    "mkdocs-git-revision-date-localized-plugin>=1.5.0,<2",
    "mkdocs-git-committers-plugin-2>=2.5.0,<3",
    "mkdocs-awesome-pages-plugin>=2.10.1,<3",
    "cairosvg>=2.8.2,<3",
    "markdown-grid-tables>=0.6.0,<0.7",
    "mkdocs-glightbox>=0.5.1,<0.6",
    "mkdocs-ezlinked-plugin>=0.3.3,<0.4",
]

[project.optional-dependencies]
brentutils = [
    "tomli-w>=1.2.0,<2",
    "beautifulsoup4>=4.14.2,<5",
    "selenium>=4.43.0,<5",
    "lxml>=6.1.0,<7",
]

[project.urls]
Repository = "https://github.com/Tech-TTGames/NINA"

[project.scripts]
start = "NINA.__main__:main"

[dependency-groups]
dev = [
    "isort>=8.0.1,<9",
    "yapf>=0.43.0,<0.44",
    "pylint>=4.0.4,<5",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["NINA"]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.yapf]
based_on_style = "google"
column_limit = 120

[tool.isort]
profile = "google"
lines_between_types = 1
