# Delete the event after adding/locating it in dixie_events.toml
[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (grabs/grabs/grabs/grabs/grab1) a shovel."
text = "$Tribute1 grabs a shovel."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (takes/takes/takes/takes/take1) a handful of throwing knives."
text = "$Tribute1 takes a handful of throwing knives."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (takes/takes/takes/takes/take1) a Mallet from inside the Oasis."
text = "$Tribute1 takes a Mallet from inside the Oasis."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (takes/takes/takes/takes/take1) a Hoe from inside the Oasis."
text = "$Tribute1 takes a Hoe from inside the Oasis."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (snatches/snatches/snatches/snatches/snatch1) a pair of Nunchucks."
text = "$Tribute1 snatches a pair of Nunchucks."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an AR-15 with ammunition."
text = "$Tribute1 grabs an AR-15 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a Vector without ammunition."
text = "$Tribute1 grabs a Vector without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a MPX with ammunition."
text = "$Tribute1 grabs a MPX with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an M4 but forgets the magazines."
text = "$Tribute1 grabs an M4 but forgets the magazines."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) picks up a Ballistic Shield."
text = "$Tribute1 picks up a Ballistic Shield."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a SPAS-12 with ammunition."
text = "$Tribute1 grabs a SPAS-12 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an AK-12 with ammunition."
text = "$Tribute1 grabs an AK-12 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs some Quartz."
text = "$Tribute1 grabs some Quartz."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) picks up a Jupiter Cannon trigger."
text = "$Tribute1 picks up a Jupiter Cannon trigger."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds an Adult Card on the ground."
text = "$Tribute1 finds an Adult Card on the ground."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs some penlights."
text = "$Tribute1 grabs some penlights."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds an unsheathed edge."
text = "$Tribute1 finds an unsheathed edge."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an AR-15 without ammunition."
text = "$Tribute1 grabs an AR-15 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a Vector with ammunition."
text = "$Tribute1 grabs a Vector with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a MPX without ammunition."
text = "$Tribute1 grabs a MPX without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an M4 along with the magazines."
text = "$Tribute1 grabs an M4 along with the magazines."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a SPAS-12 without ammunition."
text = "$Tribute1 grabs a SPAS-12 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an AK-12 without ammunition."
text = "$Tribute1 grabs an AK-12 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) picks up a UMP45 with ammunition."
text = "$Tribute1 picks up a UMP45 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) picks up a UMP45 without ammunition."
text = "$Tribute1 picks up a UMP45 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds an HK416 assault rifle with ammunition."
text = "$Tribute1 finds an HK416 assault rifle with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds an HK416 assault rifle without ammunition."
text = "$Tribute1 finds an HK416 assault rifle without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a UMP9 with ammunition."
text = "$Tribute1 grabs a UMP9 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a UMP9 without ammunition."
text = "$Tribute1 grabs a UMP9 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a AK47 with ammunition."
text = "$Tribute1 grabs a AK47 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a AK47 without ammunition."
text = "$Tribute1 grabs a AK47 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a Makarov pistol with ammunition."
text = "$Tribute1 grabs a Makarov pistol with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a Makarov pistol without ammunition."
text = "$Tribute1 grabs a Makarov pistol without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds an MP5 with ammunition."
text = "$Tribute1 finds an MP5 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds an MP5 without ammunition."
text = "$Tribute1 finds an MP5 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds a .50AE Desert Eagle with ammunition."
text = "$Tribute1 finds a .50AE Desert Eagle with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds a .50AE Desert Eagle without ammunition."
text = "$Tribute1 finds a .50AE Desert Eagle without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an MP7 with ammunition."
text = "$Tribute1 grabs an MP7 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs an MP7 without ammunition."
text = "$Tribute1 grabs an MP7 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a G36 with ammunition."
text = "$Tribute1 grabs a G36 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a G36 without ammunition."
text = "$Tribute1 grabs a G36 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) gets a P90 with ammunition."
text = "$Tribute1 gets a P90 with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) gets a P90 without ammunition."
text = "$Tribute1 gets a P90 without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a SIG MCX assault rifle with ammunition."
text = "$Tribute1 grabs a SIG MCX assault rifle with ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a SIG MCX assault rifle without ammunition."
text = "$Tribute1 grabs a SIG MCX assault rifle without ammunition."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a metal baseball bat."
text = "$Tribute1 grabs a metal baseball bat."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a spear with a laser sight attached."
text = "$Tribute1 grabs a spear with a laser sight attached."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) obtains a bulletproof vest and escapes the Oasis."
text = "$Tribute1 obtains a bulletproof vest and escapes the Oasis."
tribute_changes = [
    {},
]


[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) grabs a bipod knife."
text = "$Tribute1 grabs a bipod knife."
tribute_changes = [
    {},
]
