# Delete the event after adding/locating it in dixie_events.toml
[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) a hatchet from an unknown sponsor."
text = "$Tribute1 receives a hatchet from an unknown sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) suspicious liquids from an unknown Fr*nch sponsor."
text = "$Tribute1 receives suspicious liquids from an unknown Fr*nch sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) Diggcoins from an unknown scammer."
text = "$Tribute1 receives Diggcoins from an unknown scammer."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) fresh food from an unknown Fr*nch sponsor."
text = "$Tribute1 receives fresh food from an unknown Fr*nch sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) an explosive from an unknown bomber."
text = "$Tribute1 receives an explosive from an unknown bomber."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) candies from an unknown sugar addict."
text = "$Tribute1 receives candies from an unknown sugar addict."
tribute_changes = [
    {}
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1)'s weapon breaks."
text = "$Tribute1's weapon breaks."
tribute_changes = [
    {},
]



[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2:1) manage to sneak into (Player3!1)'s shelter and steals from (him/her3)."
text = "$Tribute1 and $Tribute2 manage to sneak into $Tribute3's shelter and steals from him."
tribute_changes = [
    {},
    {},
    {},
]



[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a packaging of ramen from an unknown sponsor."
text = "$Tribute1 receives a packaging of ramen from an unknown sponsor."
tribute_changes = [
    {},
]


[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a 1:10 Scale Gundam from an unknown NEET and starts building it."
text = "$Tribute1 receives a 1:10 Scale Gundam from an unknown NEET and starts building it."
tribute_changes = [
    {},
]
