# Delete the event after adding/locating it in dixie_events.toml
[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) a hatchet from an unknown sponsor."
text = "$Tribute1 receives a hatchet from an unknown sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) suspicious liquids from an unknown Fr*nch sponsor."
text = "$Tribute1 receives suspicious liquids from an unknown Fr*nch sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) Diggcoins from an unknown scammer."
text = "$Tribute1 receives Diggcoins from an unknown scammer."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) fresh food from an unknown Fr*nch sponsor."
text = "$Tribute1 receives fresh food from an unknown Fr*nch sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) an explosive from an unknown bomber."
text = "$Tribute1 receives an explosive from an unknown bomber."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) candies from an unknown sugar addict."
text = "$Tribute1 receives candies from an unknown sugar addict."
tribute_changes = [
    {}
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1)'s weapon breaks."
text = "$Tribute1's weapon breaks."
tribute_changes = [
    {},
]













[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) pats (Player2:1)'s head."
text = "$Tribute1 pats $Tribute2's head."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) falls off a steep cliff trying to climb down, but survives the fall."
text = "$Tribute1 falls off a steep cliff trying to climb down, but survives the fall."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) falls off a steep cliff trying to climb down, and is unconscious for the night."
text = "$Tribute1 falls off a steep cliff trying to climb down, and is unconscious for the night."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2:1) manage to sneak into (Player3!1)'s shelter and steals from (him/her3)."
text = "$Tribute1 and $Tribute2 manage to sneak into $Tribute3's shelter and steals from him."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2:1) chase after (Player3!1) but they fail to catch (him/her/them3)."
text = "$Tribute1 and $Tribute2 chase after $Tribute3 but they fail to catch him."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) chases after (Player2!1) but fails to catch (him/her/them2)."
text = "$Tribute1 chases after $Tribute2 but fails to catch him."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1), (Player2:1) and (Player3:1) chase after (Player4!1) but fail to catch (him/her4)."
text = "$Tribute1, $Tribute2 and $Tribute3 chase after $Tribute4 but fail to catch him."
tribute_changes = [
    {},
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a packaging of ramen from an unknown sponsor."
text = "$Tribute1 receives a packaging of ramen from an unknown sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) boils water over a firepit and makes ramen."
text = "$Tribute1 boils water over a firepit and makes ramen."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) laughs at (Player2!1)."
text = "$Tribute1 laughs at $Tribute2."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) argues with (Player2:1), resulting in (him/her/them2) getting kicked out of (Player1:1)'s shelter."
text = "$Tribute1 argues with $Tribute2, resulting in him getting kicked out of $Tribute1's shelter."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2) argue with (Player3:1), resulting in (Player3:1) getting kicked out of their shelter."
text = "$Tribute1 and $Tribute2 argue with $Tribute3, resulting in $Tribute3 getting kicked out of their shelter."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) gets lit and fucks the club up."
text = "$Tribute1 gets lit and fucks the club up."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) and (Player2) get lit and fuck the club up."
text = "$Tribute1 and $Tribute2 get lit and fuck the club up."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1), (Player2) and (Player3) get lit and fuck the club up."
text = "$Tribute1, $Tribute2 and $Tribute3 get lit and fuck the club up."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1), (Player2), (Player3) and (Player4) get lit and fuck the club up."
text = "$Tribute1, $Tribute2, $Tribute3 and $Tribute4 get lit and fuck the club up."
tribute_changes = [
    {},
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) burns a whole field of weed with a flamethrower."
text = "$Tribute1 burns a whole field of weed with a flamethrower."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) found some operands to repair themselves with."
text = "$Tribute1 found some operands to repair themselves with."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) pets an unknown dog sponsor riding a cart."
text = "$Tribute1 pets an unknown dog sponsor riding a cart."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a 1:10 Scale Gundam from an unknown NEET and starts building it."
text = "$Tribute1 receives a 1:10 Scale Gundam from an unknown NEET and starts building it."
tribute_changes = [
    {},
]
