# Delete the event after adding/locating it in dixie_events.toml
[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) a hatchet from an unknown sponsor."
text = "$Tribute1 receives a hatchet from an unknown sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) suspicious liquids from an unknown Fr*nch sponsor."
text = "$Tribute1 receives suspicious liquids from an unknown Fr*nch sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) Diggcoins from an unknown scammer."
text = "$Tribute1 receives Diggcoins from an unknown scammer."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) fresh food from an unknown Fr*nch sponsor."
text = "$Tribute1 receives fresh food from an unknown Fr*nch sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) an explosive from an unknown bomber."
text = "$Tribute1 receives an explosive from an unknown bomber."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks of receiving a sponsorship but first a word from today's sponsor - Raid Shadow Le--- (Player1) installed Ublock Origin"
text = "$Tribute1 thinks of receiving a sponsorship but first a word from today's sponsor - Raid Shadow Le--- $Tribute1 installed uBlock Origin"
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) (receives/receives/receives/receives/receive1) candies from an unknown sugar addict."
text = "$Tribute1 receives candies from an unknown sugar addict."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) shoots their gun at (Player2!1). (Player1) forgot to turn off the safety and (Player2) manages to escape."
text = "$Tribute1 shoots their gun at $Tribute2. $Tribute1 forgot to turn off the safety and $Tribute2 manages to escape."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) finds a plastic chair overlooking a cliff. They sit down and contemplate their life choices."
text = "$Tribute1 finds a plastic chair overlooking a cliff. They sit down and contemplate their life choices."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a help and advice guide from an unknown professor. [TypeA1] reads it and clears a Matrix Dungeon."
text = "$Tribute1 receives a help and advice guide from an unknown professor. $SP1_C reads it and clears a Matrix Dungeon."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about playing the critically acclaimed MMORPG Fin--- (Player1) installed Ublock Origin."
text = "$Tribute1 thinks about playing the critically acclaimed MMORPG Fin--- $Tribute1 installed Ublock Origin."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) wishes they got Sanctifier role."
text = "$Tribute1 wishes they got Sanctifier role."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) longs for affection."
text = "$Tribute1 longs for affection."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) trades with (Player2!1)'s district for ammunition."
text = "$Tribute1 trades with $Tribute2's district for ammunition."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) considers cannibalism."
text = "$Tribute1 considers cannibalism."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) couldn't care less about the day and goes to sleep."
text = "$Tribute1 couldn't care less about the day and goes to sleep."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about (Player2)."
text = "$Tribute1 thinks about $Tribute2."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about (Player2) and (Player3)."
text = "$Tribute1 thinks about $Tribute2 and $Tribute3."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about (Player2) who is thinking about (Player1)."
text = "$Tribute1 thinks about $Tribute2 who is thinking about $Tribute1."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about (Player2) who is thinking about (Player3)."
text = "$Tribute1 thinks about $Tribute2 who is thinking about $Tribute3."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about (Player2) who is thinking about (Player3) who is thinking about (Player4)."
text = "$Tribute1 thinks about $Tribute2 who is thinking about $Tribute3 who is thinking about $Tribute4."
tribute_changes = [
    {},
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) goes swimming in a lake."
text = "$Tribute1 goes swimming in a lake."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) practices (his/her/their1) aim in the woods."
text = "$Tribute1 practices his aim in the woods."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) sets Molotov traps around (his/her/their1) shelter."
text = "$Tribute1 sets Molotov traps around his shelter."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) reinforces their shelter with Barbed wire."
text = "$Tribute1 reinforces their shelter with Barbed wire."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) survives dysentery."
text = "$Tribute1 survives dysentery."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1)'s weapon breaks."
text = "$Tribute1's weapon breaks."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) tries to convince (Player2!1) to team up with (him/her1) but fails."
text = "$Tribute1 tries to convince $Tribute2 to team up with him but fails."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) convinces (Player2!1) to team up for the day."
text = "$Tribute1 convinces $Tribute2 to team up for the day."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) gives (Player2:1) a hug."
text = "$Tribute1 gives $Tribute2 a hug."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) pats (Player2:1)'s head."
text = "$Tribute1 pats $Tribute2's head."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) raids (Player2!1)'s shelter while (he/she/they2) would go out hunting."
text = "$Tribute1 raids $Tribute2's shelter while he would go out hunting."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) thinks about clicking to the rhythm of an anime song."
text = "$Tribute1 thinks about clicking to the rhythm of an anime song."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) falls off a steep cliff trying to climb down, but survives the fall."
text = "$Tribute1 falls off a steep cliff trying to climb down, but survives the fall."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) falls off a steep cliff trying to climb down, and is unconscious for the day."
text = "$Tribute1 falls off a steep cliff trying to climb down, and is unconscious for the day."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2:1) manage to sneak into (Player3!1)'s shelter and steals from (him/her/them3)."
text = "$Tribute1 and $Tribute2 manage to sneak into $Tribute3's shelter and steals from him."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) begins planting seeds and farming."
text = "$Tribute1 begins planting seeds and farming."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) chases after (Player2:1) but fails to catch (him/her/them2). They are playing tag."
text = "$Tribute1 chases after $Tribute2 but fails to catch him. They are playing tag."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2:1) chase after (Player3!1) but they fail to catch (him/her/them3)."
text = "$Tribute1 and $Tribute2 chase after $Tribute3 but they fail to catch him."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1), (Player2:1) and (Player3:1) chase after (Player4!1) but fail to catch (him/her4)."
text = "$Tribute1, $Tribute2 and $Tribute3 chase after $Tribute4 but fail to catch him."
tribute_changes = [
    {},
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1), (Player2:1) and (Player3:1) chase after (Player4:1) but fail to catch (him/her4). They are playing tag."
text = "$Tribute1, $Tribute2 and $Tribute3 chase after $Tribute4 but fail to catch him. They are playing tag."
tribute_changes = [
    {},
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) uses (his/her/their1) tools and goes carpenting."
text = "$Tribute1 uses his tools and goes carpenting."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a packaging of ramen from an unknown sponsor."
text = "$Tribute1 receives a packaging of ramen from an unknown sponsor."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) boils water over a firepit and makes ramen."
text = "$Tribute1 boils water over a firepit and makes ramen."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) laughs at (Player2!1)."
text = "$Tribute1 laughs at $Tribute2."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) argues with (Player2:1), resulting in (him/her/them2) getting kicked out of (Player1:1)'s shelter."
text = "$Tribute1 argues with $Tribute2, resulting in him getting kicked out of $Tribute1's shelter."
tribute_changes = [
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1:1) and (Player2) argue with (Player3:1), resulting in (Player3:1) getting kicked out of their shelter."
text = "$Tribute1 and $Tribute2 argue with $Tribute3, resulting in $Tribute3 getting kicked out of their shelter."
tribute_changes = [
    {},
    {},
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) found some operands to repair themselves with."
text = "$Tribute1 found some operands to repair themselves with."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) burns a whole field of weed with a flamethrower."
text = "$Tribute1 burns a whole field of weed with a flamethrower."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) pets an unknown dog sponsor riding a cart."
text = "$Tribute1 pets an unknown dog sponsor riding a cart."
tribute_changes = [
    {},
]

[[cycles.events]]
weight = 20
max_use = -1
max_cycle = -1
refstring = "(Player1) receives a 1:10 Scale Gundam from an unknown NEET and starts building it."
text = "$Tribute1 receives a 1:10 Scale Gundam from an unknown NEET and starts building it."
tribute_changes = [
    {},
]
